Thank you for downloading Feedjack.


Intro
------

Feedjack is a feed aggregator writen in Python using the Django web development
framework.

Like the Planet feed aggregator:

* It downloads feeds and aggregate their contents in a single site
* The new aggregated site has a feed of its own (atom and rss)
* It uses Mark Pilgrim’s excelent FeedParser
* The subscribers list can be exported as OPML and FOAF

Original FeedJack also has some advantages:

* It handles historical data, you can read old posts
* It parses a lot more info, including post categories
* It generates pages with posts of a certain category
* It generates pages with posts from a certain subscriber
* It generates pages with posts of a certain category from a certain
  subcriber
* A cloud tag/folksonomy (hype 2.0 compliant) for every page and every
  subscriber
* It uses Django templates
* The administration is done via web (using Django's kickass autogenerated
  and magical admin site), and can handle multiple planets
* Extensive use of django’s internal cache engine. Most of the time you
  will have no database hits when serving pages.

fg-fork adds even more features, which currently can be found in CHANGES
document.

See the last section of this document for links.


Dependencies
-------------

Required dependencies:

* [Python 2.7](python.org)
* [Feedparser 4.1+](feedparser.org)
* [Django 1.1+](djangoproject.com)


Optional dependencies:

* [BeautifulSoup](http://www.crummy.com/software/BeautifulSoup/)
  Used for html mangling in some themes (fern, plain).


Installation
-------------

To install feedjack just run this command:

    python setup.py install

That will install feedjack to a python site-path, so it can be used as a django
app.

After that you must set up your Feedjack static directory inside your Django
[MEDIA_URL](media_url var) directory.
It must be set in a way that Feedjack’s static directory can be reached at
"MEDIA_URL/feedjack/".

For instance, if your MEDIA_URL resolves to /var/www, and Feedjack was installed
in /usr/lib/python2.7/site-packages/feedjack, just type this:

    ln -s /usr/lib/python2.7/site-packages/feedjack/static/feedjack /var/www/feedjack

You must also add 'feedjack' in your settings.py under
[INSTALLED_APPS][installed_apps var] and then [manage.py syncdb][syncdb] from
the command line.

Then you must add an entry in your Django "urls.py" file.
Just include feedjack.urls like this:

    urlpatterns = patterns( '',
      (r'^admin/', include('django.contrib.admin.urls')),
      (r'', include('feedjack.urls')) )

After that you might want to check out /admin section to create a feedjack site,
otherwise sample default site will be created for you on the first entry.

[media_url var]: http://docs.djangoproject.com/en/dev/ref/settings/#media-url
[installed_apps var]: http://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
[syncdb]: http://docs.djangoproject.com/en/dev/ref/django-admin/#syncdb


Configuration
--------------

The first thing you want to do is add a Site. To do this just open the admin
site and create your first planet. You must use a valid address in the URL
field, since it will be used to identify the current planet when there are
multiple planets in the same instance, and to generate all the links.

Now you must add subscribers to your first planet. A subscriber is a relation
between a Feed and a Site, so when you add your first subscriber, you must also
add your first Feed by clicking in the “+” button at the right of the Feed
combobox.

Feedjack has been designed to use Django’s internal cache engine to store
database intensive data like that tagclouds, so it is highly recomended that you
configure a CACHES or CACHE_BACKEND in your Django settings (memcached, db or
file).

Now that you have everything set up, just run the feedjack_update.py script to
retrieve the data from the feeds and that’s all. Note that you must have a
memcached, db or file CACHES in order to see the updated feeds immediately.

[cache vars]: http://docs.djangoproject.com/en/dev/topics/cache/#setting-up-the-cache


Bugs, development, more info
-----------------------------

This fork (fg-fork) homepage (also a repository link):
  http://fraggod.net/code/fossil/feedjack/

Use the tickets or wiki there to report bugs and for any other feedback
concerning this fork, since they can be unrelated to the original version.

Original version is available at [feedjack site](http://www.feedjack.org/).
